image: Visual Studio 2019

platform:
  - x86

configuration:
  - Release

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"\XDAudioDevice
  - msbuild -p:configuration=release -p:platform=x86 -p:platformToolset=v141
  
after_build:
  - 7z a XDAudioDevice.7z "C:\projects\digi-xd\XDAudioDevice\Win32\release\XDAudioDevice.dll"
  - tree /F  

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: XDAudioDevice\XDAudioDevice.7z
    name: artifacts-all
